# Generated by Django 4.0.4 on 2023-01-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Team', '0006_remove_team_event_score'),
        ('Sport', '0004_alter_finalsportpoints_id_alter_sport_id'),
        ('Person', '0010_remove_person_has_avatar_remove_person_is_admin_and_more'),
        ('Event', '0003_event_closed'),
        ('University', '0006_alter_university_id_alter_universityevent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCoordinatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.university')),
            ],
        ),
        migrations.CreateModel(
            name='TeamCoordinatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.team')),
            ],
        ),
        migrations.CreateModel(
            name='SportCoordinatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.sport')),
            ],
        ),
        migrations.CreateModel(
            name='EventCoordinatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
        ),
    ]
