# Generated by Django 2.2 on 2019-08-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0003_auto_20190811_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.Person'),
        ),
    ]
