# Generated by Django 4.0.4 on 2024-03-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_event_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
