# Generated by Django 4.0.4 on 2024-05-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_event_current'),
        ('Person', '0014_historicalperson_historicalper'),
        ('Message', '0003_alter_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='event',
        ),
        migrations.CreateModel(
            name='ChanelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Message.chanel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
        ),
    ]
