# Generated by Django 4.0.4 on 2024-05-07 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0004_chanel_remove_message_event_chaneluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chanel', to='Message.chanel'),
        ),
    ]
