# Generated by Django 4.0.4 on 2024-05-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0006_alter_message_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaneluser',
            old_name='user',
            new_name='person',
        ),
    ]
