# Generated by Django 4.0.4 on 2024-05-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0014_historicalperson_historicalper'),
        ('Event', '0004_event_current'),
        ('Message', '0007_rename_user_chaneluser_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chanel',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='ChanelUser',
            new_name='ChatPerson',
        ),
        migrations.RenameField(
            model_name='chatperson',
            old_name='chanel',
            new_name='chat',
        ),
    ]
