# Generated by Django 4.0.4 on 2024-05-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0008_rename_chanel_chat_rename_chaneluser_chatperson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reciever',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Message.chat'),
            preserve_default=False,
        ),
    ]
