# Generated by Django 4.0.4 on 2024-06-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0009_remove_message_reciever_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
