# Generated by Django 2.2 on 2019-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='btn_class',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newscategory',
            name='color',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsPicture',
        ),
    ]
