# Generated by Django 2.2 on 2019-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20190708_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='btn_class',
            field=models.CharField(max_length=20),
        ),
    ]
