# Generated by Django 2.2 on 2019-07-18 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
        ('News', '0004_auto_20190708_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Event.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newscategory',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Event.Event'),
            preserve_default=False,
        ),
    ]
