# Generated by Django 2.2 on 2019-08-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSportPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C')], max_length=1)),
                ('place', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
