# Generated by Django 4.0.4 on 2024-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0004_alter_finalsportpoints_id_alter_sport_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
