# Generated by Django 4.0.4 on 2024-04-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_event_current'),
        ('Person', '0013_alter_person_user'),
        ('Sport', '0005_eventsport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.person')),
            ],
        ),
        migrations.DeleteModel(
            name='FinalSportPoints',
        ),
        migrations.RemoveField(
            model_name='eventsport',
            name='place',
        ),
        migrations.RemoveField(
            model_name='eventsport',
            name='points',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sport_type',
        ),
        migrations.AddField(
            model_name='eventsport',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventsport',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Event.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsport',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Sport.sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsport',
            name='sport_type',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='sportcordinator',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sport.sport'),
        ),
    ]
