# Generated by Django 4.0.4 on 2024-04-25 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0013_alter_person_user'),
        ('University', '0007_eventstanding_remove_university_overall_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sport', '0007_rename_sportcordinator_sportcoordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.sport'),
        ),
        migrations.AlterField(
            model_name='sportcoordinator',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person'),
        ),
        migrations.AlterField(
            model_name='sportcoordinator',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.sport'),
        ),
        migrations.CreateModel(
            name='HistoricalSportStanding',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('participated', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event_sport', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Sport.eventsport')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='University.university')),
            ],
            options={
                'verbose_name': 'historical sport standing',
                'verbose_name_plural': 'historical sport standings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
