# Generated by Django 4.0.4 on 2024-06-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0009_historicalsport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSportPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C')], max_length=1)),
                ('place', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='historicalsport',
            name='sport_type',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='sport',
            name='sport_type',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='sportcoordinator',
            name='sport_type',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C')], default='A', max_length=1),
        ),
    ]
