# Generated by Django 2.2 on 2019-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university/logo/'),
        ),
        migrations.AddField(
            model_name='university',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='university/map/'),
        ),
        migrations.DeleteModel(
            name='UniversityLogo',
        ),
    ]
