# Generated by Django 2.2 on 2019-07-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0002_auto_20190708_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
