# Generated by Django 2.2 on 2019-07-18 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
        ('University', '0004_university_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='is_host',
        ),
        migrations.CreateModel(
            name='UniversityEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.University')),
            ],
        ),
    ]
