# Generated by Django 2.2 on 2019-06-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20190620_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTemporaryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.Person')),
            ],
        ),
    ]
