# Generated by Django 2.2 on 2019-08-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0006_auto_20190813_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emergency_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
