# Generated by Django 4.0.4 on 2022-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0009_alter_person_id_alter_personavatar_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='has_avatar',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_coach',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_organizer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_player',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_sports_coordinator',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_university_coordinator',
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='person_avatars/'),
        ),
        migrations.DeleteModel(
            name='PersonAvatar',
        ),
    ]
