# Generated by Django 2.2 on 2019-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0003_university_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
