# Generated by Django 2.2 on 2019-06-17 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('University', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=13)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('is_university_coordinator', models.BooleanField(default=False)),
                ('is_sports_coordinator', models.BooleanField(default=False)),
                ('is_player', models.BooleanField(default=False)),
                ('is_coach', models.BooleanField(default=False)),
                ('has_avatar', models.BooleanField(default=False)),
                ('pending_messages', models.IntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.University')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='person_avatars/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.Person')),
            ],
        ),
    ]
