# Generated by Django 2.2.2 on 2019-08-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_person_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
