# Generated by Django 2.2.2 on 2019-08-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0005_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='University.University'),
        ),
    ]
