# Generated by Django 2.2 on 2021-09-09 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0007_person_emergency_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='person',
            name='rut',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
