# Generated by Django 2.2.2 on 2019-07-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('state', models.CharField(choices=[('MTB', 'Pendiente'), ('MIC', 'En Curso'), ('MIF', 'Terminado')], default='MTB', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Match.Match')),
            ],
        ),
    ]
