# Generated by Django 2.2.2 on 2019-07-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Match', '0001_initial'),
        ('Event', '0001_initial'),
        ('Team', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event'),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Location'),
        ),
    ]
