# Generated by Django 2.2.2 on 2019-08-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0003_matchteam_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchteam',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='Match.MatchTeam'),
        ),
    ]
