# Generated by Django 2.2.2 on 2019-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0006_match_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteam',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
