# Generated by Django 2.2.2 on 2019-08-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0002_auto_20190730_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteam',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
