# Generated by Django 2.2 on 2019-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0007_matchteam_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('MTB', 'Por jugar'), ('MIC', 'En Curso'), ('MIF', 'Jugado')], default='MTB', max_length=3),
        ),
    ]
