# Generated by Django 2.2 on 2019-08-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0009_match_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchteam',
            name='winner',
        ),
    ]
