# Generated by Django 2.2 on 2019-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0010_remove_matchteam_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
