# Generated by Django 4.0.4 on 2022-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0012_alter_match_id_alter_matchteam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='match', to='Match.matchteam'),
        ),
    ]
