# Generated by Django 4.0.4 on 2022-05-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0013_alter_match_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='teams',
        ),
        migrations.AddField(
            model_name='matchteam',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='match_teams', to='Match.match'),
            preserve_default=False,
        ),
    ]
