# Generated by Django 4.0.4 on 2022-08-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0015_rename_time_closed_match_time_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='matchteam',
            name='is_winner',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
