# Generated by Django 4.0.4 on 2022-08-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0016_remove_match_winner_match_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteam',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
