# Generated by Django 4.0.4 on 2024-05-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0019_historicalmatchteam_historicalmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatch',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('name', 'sport'), name='unique_blocking'),
        ),
    ]
