# Generated by Django 2.2 on 2019-08-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0002_finalsportpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
