sports = [
    {"name": "Atletismo salto largo", "gender": "MIX", "type": "A"},
    {"name": "Atletismo 4x100 posta", "gender": "MIX", "type": "A"},
    {"name": "Atletismo 110m vallas", "gender": "MIX", "type": "A"},
    {"name": "Atletismo 800m", "gender": "MIX", "type": "A"},
    {"name": "Atletismo 400m", "gender": "MIX", "type": "A"},
    {"name": "Atletismo 200m", "gender": "MIX", "type": "A"},
    {"name": "Atletismo 100m", "gender": "MIX", "type": "A"},
    {"name": "Natación 4x50m", "gender": "MIX", "type": "A"},
    {"name": "Natación Relevo", "gender": "MIX", "type": "A"},
    {"name": "Natación 400m", "gender": "MIX", "type": "A"},
    {"name": "Natación 200m", "gender": "MIX", "type": "A"},
    {"name": "Natación 100m", "gender": "MIX", "type": "A"},
    {"name": "Natación 50m", "gender": "MIX", "type": "A"},
    {"name": "Futbolito damas", "gender": "FEM", "type": "A"},
    {"name": "Corrida 5K varones", "gender": "MLE", "type": "A"},
    {"name": "Corrida 5K damas", "gender": "FEM", "type": "A"},
    {"name": "Tenis dobles mixto", "gender": "MIX", "type": "A"},
    {"name": "Tenis singles damas", "gender": "FEM", "type": "A"},
    {"name": "Tenis singles varones", "gender": "MLE", "type": "A"},
    {"name": "Tenis de Mesa dobles mixto", "gender": "MIX", "type": "A"},
    {"name": "Tenis de Mesa singles damas", "gender": "FEM", "type": "A"},
    {"name": "Tenis de Mesa singles varones", "gender": "MLE", "type": "A"},
    {"name": "Básquetbol varones", "gender": "MLE", "type": "A"},
    {"name": "Básquetbol damas", "gender": "FEM", "type": "A"},
    {"name": "Vóleibol varones", "gender": "MLE", "type": "A"},
    {"name": "Vóleibol damas", "gender": "FEM", "type": "A"},
    {"name": "Rugby Seven", "gender": "MIX", "type": "A"},
    {"name": "Coreografías", "gender": "MIX", "type": "A"},
    {"name": "Fútbol varones", "gender": "MLE", "type": "A"},
    {"name": "Fútbol damas", "gender": "FEM", "type": "A"},
    {"name": "Póker Texas Hold'em", "gender": "MIX", "type": "B"},
    {"name": "Ajedrez Round Robin", "gender": "MIX", "type": "B"},
    {"name": "League of Legends 5v5", "gender": "MIX", "type": "B"},
    {"name": "Dodgeball mixto", "gender": "MIX", "type": "B"},
    {"name": "Fútbol Tenis varones", "gender": "MLE", "type": "B"},
    {"name": "Fútbol Tenis damas", "gender": "FEM", "type": "B"},
    {"name": "Curve Fever", "gender": "MIX", "type": "B"},
    {"name": "Mario Kart", "gender": "MIX", "type": "B"},
    {"name": "Age of Empires", "gender": "MIX", "type": "B"},
    {"name": "Worms", "gender": "MIX", "type": "B"},
    {"name": "Rocket League", "gender": "MIX", "type": "B"},
    {"name": "Escalada varones", "gender": "MLE", "type": "B"},
    {"name": "Escalada damas", "gender": "FEM", "type": "B"},
    {"name": "Handball varones", "gender": "MLE", "type": "B"},
    {"name": "Handball damas", "gender": "FEM", "type": "B"},
    {"name": "Vóleibol Playa varones", "gender": "MLE", "type": "B"},
    {"name": "Vóleibol Playa damas", "gender": "FEM", "type": "B"},
    {"name": "FIFA 2019 dobles", "gender": "MIX", "type": "C"},
    {"name": "Super Smash Bros. Ultimate", "gender": "MIX", "type": "C"},
    {"name": "Dudo", "gender": "MIX", "type": "C"},
    {"name": "Catán", "gender": "MIX", "type": "C"},
    {"name": "Cachipún Alemán", "gender": "MIX", "type": "C"},
    {"name": "Spikeball", "gender": "MIX", "type": "C"},
    {"name": "Taca-Taca", "gender": "MIX", "type": "C"},
    {"name": "Batalla de Gallos", "gender": "MIX", "type": "C"},
    {"name": "Cubo Rubik", "gender": "MIX", "type": "C"},
    {"name": "Just Dance", "gender": "MIX", "type": "C"},
]
