# Generated by Django 2.2.2 on 2019-07-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0004_person_event'),
        ('Sport', '0001_initial'),
        ('University', '0005_auto_20190717_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.Person')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.Sport')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.University')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.Person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.Team')),
            ],
        ),
    ]
