# Generated by Django 4.0.4 on 2022-08-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_alter_playerteam_id_alter_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='event_score',
        ),
    ]
