# Generated by Django 2.2 on 2019-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20190629_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
