# Generated by Django 4.0.4 on 2022-08-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sport', '0004_alter_finalsportpoints_id_alter_sport_id'),
        ('University', '0006_alter_university_id_alter_universityevent_id'),
        ('Event', '0002_alter_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(default=0)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.sport')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='University.university')),
            ],
        ),
        migrations.CreateModel(
            name='EventPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='University.university')),
            ],
        ),
    ]
