# Generated by Django 4.0.4 on 2022-08-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportplacement',
            name='participated',
            field=models.BooleanField(default=True),
        ),
    ]
