# Generated by Django 4.0.4 on 2022-08-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_event_id'),
        ('Placement', '0004_eventplacement_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportplacement',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sport_placements', to='Event.event'),
            preserve_default=False,
        ),
    ]
